"""empty message

Revision ID: 86528e9a8aaa
Revises: 
Create Date: 2021-08-31 18:33:26.793052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86528e9a8aaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('deckName', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_to_deck',
    sa.Column('deckId', sa.Integer(), nullable=False),
    sa.Column('cardId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cardId'], ['userCards.id'], ),
    sa.ForeignKeyConstraint(['deckId'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('deckId', 'cardId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_to_deck')
    op.drop_table('decks')
    # ### end Alembic commands ###
